### ISSUE TITLE
More robust handling of types in the presence of duplicate protobuf blobs

### ISSUE THREAD

**Issue by zenhack** [bobg/bs#3]
Right now, if two typed blobs with different types but the same content are stored, one of the types will simply "win," and the exact behavior seems to be backend specific. This seems sub-optimal.

When we add GC, this will be even more problematic, as the store needs to care about the types to find edges.

If we end up going the route of having a special `Ref` type for GC, maybe we could add the type to the ref itself, i.e.

```protobuf
message Ref {
  bytes contentHash = 1;
  bytes typeHash = 2;
}
```

Thoughts?

**Comment by bobg** [comment]
Great point about colliding types for identical blobs. I have the germ of an idea about how to address it but I have to mull it over a bit before I'll be ready to share it. Thanks for the insight!

**Comment by bobg** [comment]
> I have the germ of an idea about how to address it

Well, never mind about that - I thought I could make type annotations themselves be blobs (the way anchors are) in a pleasingly metacircular way but that turns out not to buy you anything; the store still needs exactly as much type-aware magic with or without those blobs. So I simply made types per blob be many-to-one and this is closed as of https://github.com/bobg/bs/commit/bc7b3e58db2586526c5c0d54808dcd098acbc793.
